/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.8.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_verifyDiscordKey from "../actions/verifyDiscordKey";
import type * as botResponses from "../botResponses";
import type * as http from "../http";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/verifyDiscordKey": typeof actions_verifyDiscordKey;
  botResponses: typeof botResponses;
  http: typeof http;
}>;
